# Generated by Django 4.1.6 on 2023-02-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, null=True)),
                ("price", models.FloatField(null=True)),
            ],
        ),
    ]
